aws:
  AWS_ACCESS_KEY_ID = 'AKIAJ7QH2MBKN3GV6HEQ'
  AWS_SECRET_ACCESS_KEY = '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'
  AWS_DEFAULT_REGION = 'us-west-2'

twitter_search_api: 
  TW_consumer_key='PDZVXDgrwvRONdprGcY8OWU4I'
  TW_consumer_secret='gPNmKpQC0h7yEK3nL0rrdF6h8SaEDSu0pNa33YOAa9OWJywIGB'
  TW_access_token='1198146755092787201-NKeQ7z8OTvcGrqBZMGn3F3Bx1nb2Ag'
  TW_access_token_secret='SR8sxjUcENjJWRPb1PxL7eRO2xJxqHmutezbURGm3Cb9x'
  TW_bearer_token='AAAAAAAAAAAAAAAAAAAAAEEGBgEAAAAA2sgufa%2B%2FabpGWqojZfN8rdX%2FHpU%3DZPRL7FUqY9K3LAldcSsqi5Dejxxg7UBqPnsGaqIlmymsTzhTiL'
